### PR TITLE
Split source into multiple files

### LINKED ISSUE #46: Split source code into multiple files
An important step towards v0.1.0 - and also community contributions - is making the codebase easier to work with in general. Now that we have the package manager, we can split the source into multiple files and make tablex development more accessible.

### PR DESCRIPTION
**Pull request by PgBiel**
Closes #46

Should make the code easier to work with.

### CODE REVIEW

**Comment by emilyyyylime** [comment]
Is this up to date?
I'm thinking of contributing and I'd much rather base my contributions off of this version

**Comment by PgBiel** [comment]
@emilyyyylime not yet (it wasn't yet updated for 0.0.5). Feel free to ping me on the weekend and I might be able to find some time for it

**Comment by emilyyyylime** [comment]
:sweat_smile: I'll have to try and remember

**Comment by PgBiel** [comment]
Did some (unscientific) benchmarks, and seems like these changes _do not_ slow down tablex compilation in any way (the time to compile `tablex-test.typ` was the same on main and on `separation`).

**Pull request merged**
