### PR TITLE
doc(known-issues): Add caveat about layout/hyphenation of rotated text

### PR DESCRIPTION
**Pull request by ja-he**
Per discussion in https://github.com/PgBiel/typst-tablex/issues/59.

I figured I could make myself useful by writing down what I tried to find before filing the issue.

Feel free to edit this or suggest edits as you prefer them or reject the PR, just my quick idea for a bit of doc.

### CODE REVIEW

**Comment by ja-he** [comment]
@PgBiel in #59 you suggested trying `box`, which I could not make work.
If you're convinced that it should work _somehow_, that would obviously be a better workaround than what I document in this PR, so you may want to see about that before blindly accepting my first-thing-that-worked advice :slightly_smiling_face:

**Comment by ja-he** [comment]
Sorry, realized that your box-suggestion was the way to go after all, so I wanted to add that as well.
Feel free to squash the commits (or tell me to squash them) as you see fit.

**Comment by PgBiel** [comment]
Don't worry about the commits. :)

**Comment by PgBiel** [comment]
I think another possible workaround might be to use `#place` so the text doesn't occupy any space at all, thus allowing for more flexibility. We could perhaps mention both approaches.

**Comment by PgBiel** [comment]
Other than that, your text is pretty good. Thanks!

**Comment by ja-he** [comment]
> I think another possible workaround might be to use `#place` over the `rotate` so the text doesn't occupy any space at all, thus allowing for more flexibility. We could perhaps mention both approaches. (This should be tested first, though.)

I got the result I wanted and also got with `box` and `hyphenate:false` via `rowspanx(7, box(rotate(-90deg, [...])))` so I added that to the text.

Again, feel free to edit as you want.

**Comment by PgBiel** [comment]
Thank you! :D

**Pull request merged**
